### PR TITLE
Support of Uint8Array added

### PR DESCRIPTION
**Pull request by saferif**

### CODE REVIEW

**Comment by jameshartig** [comment]
Thanks for this! Can you add a test? Also, you need to rebase, I removed Node 0.8, 0.6 from the Travis file.

**Comment by saferif** [comment]
I have rebased my commit and added a test similar to the ones that were already there.

**Comment by jameshartig** [comment]
Awesome! Just one other thing I didn't notice before... can you add:

``` JS
HAS_UINT8ARRAY = (typeof UInt8Array !== 'undefined')
```

just like how the `HAS_BUFFER` is defined and used? Then use `HAS_UINT8ARRAY` in the ifs before the `instanceof` checks.

Otherwise if this is run in a browser that doesn't have `UInt8Array`, it'll throw an error since you can't do `instanceof undefined`.

**Comment by saferif** [comment]
Yes, it's good idea. But in the current code I see:

``` javascript
var HAS_BUFFERS = (typeof 'Buffer' !== 'undefined'),
    undefined;
```

Isn't it, that `typeof 'Buffer'` is always `string`? And I don't actually understand the purpose of `undefined` after the comma.

**Comment by jameshartig** [comment]
Woops! :P Might as well fix that to be:

``` JS
HAS_BUFFERS = (typeof Buffer !== 'undefined')
```

The `undefined` after the comma is just a prevention against someone overwriting `undefined` on the window (which some browsers allow) and breaking the meaning of it.

**Comment by jameshartig** [comment]
Merged. Thanks @saferif!

**Comment by jameshartig** [comment]
@saferif this has been published in 0.0.2. Sorry for the delay. I forgot to publish the new version after merging.

**Pull request merged**
